Create adicionar-nova-vaga.md
backend-br/vagas pull request #2353
Opened 2020-04-19 02:02 UTC by Renato66

Algumas empresas fazem uma descrição muito breve da vaga, com esse template eles teriam um guia para seguir

2020-04-19 03:22 UTC, guibranco requested changes
Na linha 10 está com a frase: POR FAVOR, SÓ POSTE SE A VAGA FOR PARA FRONT-END!

O certo não seria: POR FAVOR, SÓ POSTE SE A VAGA FOR PARA BACK-END! ?

2020-04-19 03:27 UTC, guibranco approved these changes

2020-04-19 19:13 UTC, ssgoncalves approved these changes

2020-06-05 15:56 UTC, mrprompt approved these changes

2020-06-18 15:15 UTC, reginaldojunior approved these changes

2020-06-18 15:15 UTC, reginaldojunior commented
Daora, tá mergeado!

2020-06-18 15:15 UTC, merged